{['../src/*',
 '../src/*/*',
 '../src/*/*/*'],
 [{i, "../include"}, {outdir, "../ebin"}, nowarn_unused_vars, nowarn_unused_funtion, native, {hipe, [o3]}]}.
 
{['./*'],
 [{i, "../include"}, {outdir, "../ebin"}, nowarn_unused_vars, nowarn_unused_funtion, native]}.
