{['../src/*',
 '../src/*/*',
 '../src/*/*/*'],
 [{i, "../include"}, {outdir, "../ebin"},{d,debug},
 debug_info, nowarn_unused_vars, nowarn_unused_funtion]}.
 
%%{['./*'],
%% [{i, "../include"}, {outdir, "../ebin"}, nowarn_unused_vars, nowarn_unused_funtion, native]}.
